### PR TITLE
fix:Fix the url returned to the previous page in the network strategy

### LINKED ISSUE #556: Click Network Policy to get back to the previous page while leading to the project page
**Describe the bug**
In the Network Policy info page, click Network Policy to get back to the previous page but it leads to the Project page.

**Environment**

KubeSphere web console

**To Reproduce**
1. Go to Network Policies and click any policy.

2. In this page,  click Network Policy to get back to the previous page.

3. This will lead to the Project where the network policy is set.

I think for Step 3 it should lead to the page in step 1? Or is it expected to lead to the Project page?

### PR DESCRIPTION
**Pull request by harrisonliu5**
**What type of PR is this?**

/kind bug

**Which issue(s) this PR fixes**:

Fixes #556 

/assign @leoendless

### CODE REVIEW

File: src/pages/projects/containers/Network/Policies/Detail/index.jsx [hunk 1]
```diff
@@ -139,7 +145,7 @@ export default class NetworkpoliciesDetail extends React.Component {
       breadcrumbs: [
         {
           label: t(this.name),
-          url: this.listUrl,
+          url: `/clusters/${this.cluster}/networkpolicies`,
```
Comment (leoendless) [inline src/pages/projects/containers/Network/Policies/Detail/index.jsx:148]: you need to check if it works right in project.
