### PR TITLE
fix: Certificate verification problem

### LINKED ISSUE #2696: Certificate verification problem
**Describe the Bug**

image

**Versions Used**
KubeSphere: kubesphere v3.2.1
Kubernetes: (If KubeSphere installer used, you can skip this)

/assign @LinuxSuRen 
/kind bug
/priority Low
/area devops

### PR DESCRIPTION
**Pull request by mangoGoForward**
Signed-off-by: mango <xu.weiKyrie@foxmail.com>

### What type of PR is this?

/kind bug

### What this PR does / why we need it:
Please see #2696. 
When verify credential, only display the type is equip to `username_password` 

### Which issue(s) this PR fixes:

Fixes ##2696

### Does this PR introduced a user-facing change?

```release-note
None
```

### CODE REVIEW

File: src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx [hunk 1]
```diff
@@ -157,11 +157,13 @@ export default class GitHubForm extends React.Component {
...
-        value: credential.name,
-        type: credential.type,
-      })),
+      ...this.props.store.credentials.data
+        .map(credential => ({
+          label: credential.name,
+          value: credential.name,
+          type: credential.type,
+        }))
+        .filter(credential => credential.type === 'username_password'),
```
Comment (JohnNiang) [inline src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx:166]: IMO, the type of credential should be `credential.devops.kubesphere.io/basic-auth` instead of `username_password`. Please see:

image

**Review by JohnNiang — CHANGES_REQUESTED** [review]

File: src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx (hunk 1 above)
Comment (JohnNiang) [reply src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx:166]: If I missed something, please feel free to correct me.

Comment (JohnNiang) [reply src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx:166]: I found that the credential list is transformed by:

https://github.com/kubesphere/console/blob/cf09f369c727dada8d12db2ca3b901c48fdb4a7a/src/stores/devops/credential.js#L94-L97

My bad! You are right.

**Review by JohnNiang — APPROVED** [review]
/lgtm

I confirm that this PR fixes that issue very well.

image
image

File: src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx (hunk 1 above)
Comment (mangoGoForward) [reply src/components/Forms/Pipelines/RepoSelect/GithubForm/index.jsx:166]: Yes, the data was transformed.
