### PR TITLE
fix: Fix the data is empty in GitLab

### LINKED ISSUE #1466: When creating a pipeline through GitLab, the popover will suddenly disappear.
**Describe the Bug**
image

**Environment**
http://allinone:8080

**Preset conditions**
There is a devops 'dev1'

**How To Reproduce**
1. Go to devops 'dev1'
2. Click on 'Create'
3. After enter name, click 'Select Code Repository'
4. Click 'GitLab'
5. Select GitLab server
6. Input owener
7. Click anywhere in the popover

**Expected behavior**
The popover doesn't disappear

**Actual behavior**
The popover disappeared

/priority high
/area devops
/cc @harrisonliu5 
/kind bug
/milestone 3.1.0

### PR DESCRIPTION
**Pull request by harrisonliu5**
Signed-off-by: harrisonliu5 <harrisonliu_5@163.com>

**What type of PR is this?**

 /kind bug

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #1466 

**Special notes for reviewers**:

```
```

**Additional documentation, usage docs, etc.**:

```docs

```

/assign @leoendless

### CODE REVIEW

File: src/stores/devops/scm.js [hunk 1]
```diff
@@ -379,12 +379,14 @@ export default class SCMStore extends BaseStore {
...
-    if (result.status === 'ok' && isArray(result.data)) {
-      serverList =
-        !isEmpty(result.data) &&
-        result.data.map(item => {
-          return { label: item.name, value: item.name }
-        })
+    if (
+      result.status === 'ok' &&
+      isArray(result.data) &&
+      !isEmpty(result.data)
```
Comment (leoendless) [inline src/stores/devops/scm.js:385]: It seems unnecessary to check whether the array is empty

Comment (harrisonliu5) [reply src/stores/devops/scm.js]: done
